backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)
media_folder: static/img
public_folder: /img
collections:
  - name: 'docs'
    label: 'Docs'
    folder: 'content/docs'
    create: true
    slug: '{{slug}}'
    editor:
      preview: false
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Description', name: 'description', widget: 'string' }
      - { label: 'Body', name: 'body', widget: 'markdown' }
  - name: pages
    label: Pages
    editor:
      preview: false
    files:
      - label: Index Page
        name: index
        file: content/_index.md
        fields:
          - { label: 'Title', name: 'title', widget: hidden, default: 'Home' }
          - { label: 'Body', name: 'body', widget: 'markdown' }
      - label: About Page
        name: about
        file: content/about.md
        fields:
          - { label: 'Title', name: 'title', widget: hidden, default: 'About' }
          - { label: 'Permalink', name: 'permalink', widget: 'string', default: '/about/' }
          - { label: 'Body', name: 'body', widget: 'markdown' }
